#!/bin/bash
function findWine(){
	echo "BakkesHelper: Locating Proton wine executable" >&2
	ret="$(cat "$COMPATDIR/config_info" 2>/dev/null | head -2 | tail -1 | sed -s "s@/share/fonts/@@")"
	echo BakkesHelper: ret: $ret >&2
	#ret="$(cat "$COMPATDIR/config_info" 2>/dev/null | head -2 | tail -1 | grep -o ".*compatibilitytools.d/[^/]*" | head -1)"
	if [ -z "$ret" ]; then
		echo "BakkesHelper: ERROR: Could not locate Proton wine executable." >&2
		exit 1
	fi
	test -f "$ret/bin/wine"
	if [ "$?" -gt 0 ]; then
		echo "BakkesHelper: ERROR: No wine executable found at path specified in $COMPATDIR/config_info" >&2
		exit 1
	fi
	echo "$ret/bin/wine"
}



function findCompatDir(){
	echo "BakkesHelper: Locating RocketLeague prefix" >&2


	# check all steam library directories mentioned in libraryfolders.vdf for Rocket League prefix, return the first instance found or error out
	while read -r path; do
		test -d "$path/steamapps/compatdata/252950/pfx"
		if [ "$?" -eq 0 ]; then
			echo "$path/steamapps/compatdata/252950"
			return 0
		fi
	done < <(cat ~/".steam/root/steamapps/libraryfolders.vdf" | grep "\"path\"" | grep -oP "[^\s]*$" | sed -s "s/\"//g")
	echo "BakkesHelper: No Rocket League installation found." >&2
	exit 1
}



function installBakkes(){
	# download, unzip latest BakkesMod
	wget -q --show-progress https://github.com/bakkesmodorg/BakkesModInjectorCpp/releases/latest/download/BakkesModSetup.zip
	unzip BakkesModSetup.zip

	# launch installer
	WINEPREFIX="$ROCKETDIR" "$ROCKETWINE" "BakkesModSetup.exe"

	# check if installation was successful
	test -e "$ROCKETDIR/drive_c/Program Files/BakkesMod/BakkesMod.exe"
	if [ "$?" -gt 0 ]; then
		echo "BakkesHelper: ERROR: BakkesMod not installed for unknown reasons. Maybe user cancelled setup?" >&2
		return 1
	else
		echo "BakkesHelper: BakkesMod installed successfully." >&2

		# update config file tracking installed version
		echo "$BAKKESVER" > ~/".config/bakkes/version"
		echo "BakkesHelper: Config updated to reflect current version: $BAKKESVER" >&2
		return 0
	fi
}


# make sure config directory exists
mkdir -p ~/.config/bakkes

# temporary working directory
cd "$(mktemp -d)"


# check for dependencies
which unzip >/dev/null 2>/dev/null || { echo "BakkesHelper: ERROR: Install unzip from your package manager to continue" >&2; exit 1; }
which git >/dev/null 2>/dev/null || { echo "BakkesHelper: ERROR: Install git from your package manager to continue" >&2; exit 1; }
which wget >/dev/null 2>/dev/null || { echo "BakkesHelper: ERROR: Install wget from your package manager to continue" >&2; exit 1; }



# Find Rocket League prefix
COMPATDIR="$(findCompatDir)"
if [ "$?" -gt 0 ]; then
	exit 1
fi
ROCKETDIR="$COMPATDIR/pfx"
echo "BakkesHelper: CDIR: $COMPATDIR" >&2
echo "BakkesHelper: RDIR: $ROCKETDIR" >&2



# Find Proton wine executable
ROCKETWINE="$(findWine)"
if [ "$?" -gt 0 ]; then
	exit 1
fi
echo "BakkesHelper: RWINE: $ROCKETWINE" >&2


# Check if BakkesMod is installed and if version matches latest release
BAKKESCURR="$(cat ~/".config/bakkes/version")"
BAKKESVER="$(LD_PRELOAD="" LD_LIBRARY_PATH="" git ls-remote --heads "https://github.com/bakkesmodorg/BakkesModInjectorCpp" | grep "refs/heads/master" | grep -oP "^[^\s]*")"
attempts=5
while [ -z "$BAKKESVER" ]; do
	echo "BakkesHelper: ERROR: Could not get remote BakkesMod version from official repo (no internet connection?), retrying..." >&2
	sleep 5
	if [ "$attempts" -gt 0 ]; then
		attempts="$(($attempts-1))"
	else
		
		echo "BakkesHelper: ERROR: Could not get remote BakkesMod version from official repo (no internet connection?), giving up." >&2
		exit 1
	fi
	BAKKESVER="$(LD_PRELOAD="" LD_LIBRARY_PATH="" git ls-remote --heads "https://github.com/bakkesmodorg/BakkesModInjectorCpp" | grep "refs/heads/master" | grep -oP "^[^\s]*")"
done
test -e "$ROCKETDIR/drive_c/Program Files/BakkesMod/BakkesMod.exe"
if [ "$?" -gt 0 ]; then
	echo "BakkesHelper: BakkesMod not installed, installing now..." >&2
	installBakkes
	if [ "$?" -gt 0 ]; then
		echo Exiting.
		exit 1
	else
		echo Success.
	fi
else
	echo "BakkesHelper: Found BakkesMod installation, checking version." >&2
	echo "BakkesHelper: Remote BakkesMod version: $BAKKESVER" >&2
	echo "BakkesHelper: Current BakkesMod version: $BAKKESCURR" >&2
	if [ "$BAKKESCURR" != "$BAKKESVER" ]; then
		echo "BakkesHelper: BakkesMod Version mismatch, reinstalling." >&2
		installBakkes
		if [ "$?" -gt 0 ]; then
			echo "BakkesHelper: Exiting." >&2
			exit 1
		else
			echo "BakkesHelper: Installed BakkesMod." >&2
		fi
	else
		echo "BakkesHelper: BakkesMod up to date." >&2
	fi
fi

# Spawn process to wait for user to launch Rocky
cd "$(mktemp -d)"
cat > runner.sh << EOF
#!/bin/bash
while [ -z "\$(ps -e | grep RocketLeague)" ]; do
		echo "BakkesHelper: Waiting for user to start RocketLeague" >&2
		sleep 2
done
echo "BakkesHelper: RocketLeague launched" >&2
sleep 20
WINEPREFIX="$ROCKETDIR" "$ROCKETWINE" "$ROCKETDIR/drive_c/Program Files/BakkesMod/BakkesMod.exe" &
while [ ! -z "\$(ps -e | grep RocketLeague)" ]; do
	echo "BakkesHelper: RocketLeague still running." >&2
	sleep 10
done
echo "BakkesHelper: Rocket League close, shutting down." >&2
pkill -e BakkesMod
EOF
chmod +x runner.sh
./runner.sh &
